WTD/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', views.video, name='video'),
    path("home/", include('home.urls')),
    path('progress/', include('progress.urls')),
    path('result/', include('result.urls')),
]

home/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'home'
urlpatterns = [
    path('intro/', views.intro, name='intro'),
    path('', views.index, name='index'),
]

progress/urls.py
from django.urls import path
from . import views

app_name = 'progress'
urlpatterns = [
    path('', views.progress_list, name="progress_list"),
    path('step1/', views.step_1, name="step1"),
    path('step2/', views.step_2, name="step2"),
    path('step3/', views.step_3, name="step3"),
    path('step4/', views.step_4, name="step4"),
    path('step5/', views.step_5, name="step5"),
]

result/urls.py
from django.urls import path
from . import views

app_name = 'result'
urlpatterns = [
    path('', views.result_list, name="result_list"),
    path('show1/', views.show_1, name="show1"),
    path('show2/', views.show_2, name="show2"),
    path('show3/', views.show_3, name="show3"),
    path('show4/', views.show_4, name="show4"),
    path('show5/', views.show_5, name="show5"),
]

home/models.py
from django.db import models

# Create your models here.

progress/models.py
from django.db import models


class Post(models.Model):
    title = models.CharField(max_length=100, verbose_name="Title")
    content = models.TextField(verbose_name="Content")
    imgfile = models.ImageField(null=True, upload_to="", blank=True)

    def __str__(self):
        return f'[{self.pk}]{self.title}'

    class Meta:
        db_table = 'Progress'
        verbose_name = 'Progress'
        verbose_name_plural = 'Progress'

result/models.py
from django.db import models


class Show(models.Model):
    title = models.CharField(max_length=100, verbose_name="Title")
    content = models.TextField(verbose_name="Content")
    imgfile = models.ImageField(null=True, upload_to="", blank=True)

    def __str__(self):
        return f'[{self.pk}]{self.title}'

    class Meta:
        db_table = 'Result'
        verbose_name = 'Result'
        verbose_name_plural = 'Result'

home/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    return render(request, 'index.html')


def video(request):
    return render(request, 'video.html')


def intro(request):
    return render(request, 'intro.html')

progress/views.py
from django.shortcuts import render
from progress.models import Post


def progress_list(request):
    post1 = Post.objects.get(pk=1)
    post2 = Post.objects.get(pk=2)
    post3 = Post.objects.get(pk=3)
    post4 = Post.objects.get(pk=4)
    post5 = Post.objects.get(pk=5)
    return render(request, 'progress_list.html', {'post1': post1, 'post2': post2, 'post3': post3, 'post4': post4, 'post5': post5})


def step_1(request):
    post = Post.objects.get(pk=1)
    return render(request, 'step_1.html', {'post': post})


def step_2(request):
    post = Post.objects.get(pk=2)
    return render(request, 'step_2.html', {'post': post})


def step_3(request):
    post = Post.objects.get(pk=3)
    return render(request, 'step_3.html', {'post': post})


def step_4(request):
    post = Post.objects.get(pk=4)
    return render(request, 'step_4.html', {'post': post})


def step_5(request):
    post = Post.objects.get(pk=5)
    return render(request, 'step_5.html', {'post': post})

result/views.py
from django.shortcuts import render
from result.models import Show


def result_list(request):
    return render(request, 'result_list.html')


def show_1(request):
    show = Show.objects.get(pk=1)
    return render(request, 'show_1.html', {'show': show})


def show_2(request):
    show = Show.objects.get(pk=2)
    return render(request, 'show_2.html', {'show': show})


def show_3(request):
    show = Show.objects.get(pk=3)
    return render(request, 'show_3.html', {'show': show})


def show_4(request):
    show = Show.objects.get(pk=4)
    return render(request, 'show_4.html', {'show': show})


def show_5(request):
    show = Show.objects.get(pk=5)
    return render(request, 'show_5.html', {'show': show})

home/templates/index.html
{% extends 'base.html' %}
{% block content %}
<header>
    <h1 class="site-heading text-center text-faded d-none d-lg-block">
        <span class="site-heading-upper text-primary mb-3">WTD</span>
    </h1>
</header>
{% include 'navbar.html' %}
<!-- ======= Hero Section ======= -->
<section id="hero" class="d-flex align-items-center justify-content-center">
<div class="container" data-aos="fade-up">
    <div class="row justify-content-center" data-aos="fade-up" data-aos-delay="150">
    <div class="col-xl-6 col-lg-8">
        <h1>2019 <span>vs</span> 2022년</h1>
        <h1>천만 영화 흥행 요인 분석</h1>
        <h2>기생충(2019)과 범죄도시2(2022)</h2>
    </div>
    </div>
</div>
</section><!-- End Hero -->

<!-- ======= Team Section ======= -->
<section id="team" class="team">
<div class="container" data-aos="fade-up">

    <div class="section-title">
        <h2>Team</h2>
        <p>Our Team Members</p>
    </div>

    <div class="row">

    <div class="col-lg-3 col-md-6">
        <div class="member" data-aos="fade-up" data-aos-delay="100">
            <div class="member-img">
                <img src="" class="img-fluid" alt="">
            </div>
            <div class="member-info">
                <h4>김태현</h4>
                <li>웹 크롤링</li>
                <li>데이터 전처리</li>
                <li>데이터 분석</li>
                <li>데이터 시각화</li>
                <li>PPT 제작</li>
            </div>
        </div>
    </div>

    <div class="col-lg-3 col-md-6">
        <div class="member" data-aos="fade-up" data-aos-delay="200">
            <div class="member-img">
                <img src="" class="img-fluid" alt="">
            </div>
            <div class="member-info">
                <h4>방승현 (팀장)</h4>
                <li>웹 크롤링</li>
                <li>데이터 전처리</li>
                <li>데이터 분석</li>
                <li>데이터 시각화</li>
                <li>웹페이지 구축</li>
            </div>

        </div>
    </div>

    <div class="col-lg-3 col-md-6">
        <div class="member" data-aos="fade-up" data-aos-delay="300">
        <div class="member-img">
            <img src="" class="img-fluid" alt="">
        </div>
        <div class="member-info">
            <h4>이승호</h4>
            <li>PPT 제작</li>
            <li>PPT 발표</li>
        </div>
        </div>
    </div>

    <div class="col-lg-3 col-md-6">
        <div class="member" data-aos="fade-up" data-aos-delay="400">
        <div class="member-img">
            <img src="" class="img-fluid" alt="">
        </div>
        <div class="member-info">
            <h4>허다정</h4>
            <li>웹 크롤링</li>
            <li>데이터 전처리</li>
            <li>데이터 분석</li>
            <li>데이터 시각화</li>
            <li>웹페이지 구축</li>
        </div>
        </div>
    </div>

    </div>
</div>
</section><!-- End Team Section -->
{% endblock %}

home/templates/intro.html
{% extends 'base.html' %}
{% block content %}
{% include 'header.html' %}
{% include 'navbar.html' %}
{% load static %}
<!-- ##### Blog Wrapper Start ##### -->
    <div class="blog-wrapper section-padding-100">
        <div class="container">
            <div class="row align-items-end">
                <!-- Single Blog Area -->
                <div class="col-12 col-lg-4">
                    <div class="single-blog-area mb-100">
                        <!-- Blog Content -->
                        <div class="single-blog-content">
                            <div class="line"></div>
                            <a class="post-tag">2019년의 세계적인 히트작, 기생충</a>
                            <a class="post-tag">그 이후 최초의 천만 영화, 범죄도시2</a>
                            <a class="post-tag"><br></a>
                            <h4><a class="post-headline">어떻게 흥행에 성공할 수 있었을까?</a></h4>
                            <p>소셜 빅데이터를 분석해서 2019년도에 기생충이 세계적으로 성공한 이유와
                                그 이후 최초의 천만관객을 돌파한 범죄도시2의 흥행요인을 분석해보자</p>
                        </div>
                    </div>
                </div>
                <!-- Single Blog Area -->
                <div class="col-12 col-md-6 col-lg-4">
                    <div class="single-catagory-area mb-100">
                        <img src="{% static 'assets/img/기생충 포스터.png' %}" alt="">
                    </div>
                </div>
                <!-- Single Blog Area -->
                <div class="col-12 col-md-6 col-lg-4">
                    <div class="single-catagory-area mb-100">
                        <img src="{% static 'assets/img/범죄도시2 포스터.png' %}" alt="">
                    </div>
                </div>
            </div>
        </div>
    </div>

  <!-- ======= Why Us Section ======= -->
  <section id="why-us" class="why-us">
    <div class="container">

      <div class="row no-gutters">

        <div class="col-lg-4 col-md-6 content-item">
          <span>01</span>
          <h4>웹 크롤링</h4>
          <p>네이버, 다음 영화, IMDB, Rotten Tomatoes에서 Review&별점 수집 및 크롤링 모듈화 진행</p>
        </div>

        <div class="col-lg-4 col-md-6 content-item">
          <span>02</span>
          <h4>워드 클라우드</h4>
          <p>텍스트 전처리 후, 빈도수 많은 단어를 통해 흥행 요인 키워드 추측 및 시각화</p>
        </div>

        <div class="col-lg-4 col-md-6 content-item">
          <span>03</span>
          <h4> 감성분석</h4>
          <p>각 리뷰의 별점과 긍정어, 부정어 포함 정도에 따른 긍/부정 라벨링 & 예측모델 구현</p>
        </div>

        <div class="col-lg-4 col-md-6 content-item">
          <span>04</span>
          <h4>흥행요인분석</h4>
          <p>워드 클라우드 결과와 감성분석을 토대로 도출된 흥행 키워드들에 대한 추가 분석</p>
        </div>

        <div class="col-lg-4 col-md-6 content-item">
          <span>05</span>
          <h4>유사한 영화 추천</h4>
          <p>범죄도시2/기생충 흥행요인을 통한 줄거리 기반 코사인 유사도 영화 추천</p>
        </div>

        <div class="col-lg-4 col-md-6 content-item">
            <span></span>
            <h4></h4>
            <p></p>
          </div>

      </div>

    </div>
  </section><!-- End Why Us Section -->
{% endblock %}

progress/templates/progress_list.html
{% extends 'base.html' %}
{% block content %}
{% include 'header.html' %}
{% include 'navbar.html' %}
{% load static %}
<!-- Page Wrapper -->
<div id="page-wrapper">
    <!-- Banner -->
    <section id="banner">
        <div class="inner">
            <div class="logo"><span class="icon fa-gem"><i class="fa-regular fa-folder-open"></i></span></div>
            <h2>데이터 분석 5 STEPS</h2>
        </div>
    </section>

    <!-- Wrapper -->
    <section id="wrapper">

        <!-- One -->
        <section id="one" class="wrapper spotlight style1">
            <div class="inner">
                <a href="{% url 'progress:step1' %}" class="image"><img src="{% static 'assets/img/imdb크롤링.jpeg' %}" alt="" /></a>
                <div class="content">
                    <h2 class="major">STEP 1. 웹 크롤링</h2>
                    <p>{{ post1.content }}</p><br>

                   <a href="{% url 'progress:step1' %}">Learn more</a>
                </div>
            </div>
        </section>

        <!-- Two -->
        <section id="two" class="wrapper alt spotlight style2">
            <div class="inner">
                <a href="{% url 'progress:step2' %}" class="image"><img src="{% static 'assets/img/네이버관객워드클라우드(2).jpeg' %}" alt="" /></a>
                <div class="content">
                    <h2 class="major">STEP 2. 워드 클라우드</h2>
                    <p>{{ post2.content }}</p><br>
                    <a href="{% url 'progress:step2' %}" class="special">Learn more</a>
                </div>
            </div>
        </section>

        <!-- Three -->
        <section id="three" class="wrapper spotlight style3">
            <div class="inner">
                <a href="{% url 'progress:step3' %}" class="image"><img src="{% static 'assets/img/네이버관객감성머신러닝(1).jpeg' %}" alt="" /></a>
                <div class="content">
                    <h2 class="major">STEP 3. 감성분석</h2>
                    <p>{{ post3.content }}</p><br>
                    <a href="{% url 'progress:step3' %}" class="special">Learn more</a>
                </div>
            </div>
        </section>

        <!-- Four -->
        <section id="four" class="wrapper alt spotlight style4">
            <div class="inner">
                <a href="{% url 'progress:step4' %}" class="image"><img src="{% static 'assets/img/흥행요인분석.jpg' %}" alt="" /></a>
                <div class="content">
                    <h2 class="major">STEP 4. 흥행요인분석</h2>
                    <p>{{ post4.content }}</p><br>
                    <a href="{% url 'progress:step4' %}" class="special">Learn more</a>
                </div>
            </div>
        </section>

        <!-- Five -->
        <section id="five" class="wrapper spotlight style5">
            <div class="inner">
                <a href="{% url 'progress:step5' %}" class="image"><img src="{% static 'assets/img/유사도분석추천.jpg' %}" alt="" /></a>
                <div class="content">
                    <h2 class="major">STEP 5. 유사한 영화 추천</h2>
                    <p>{{ post5.content }}</p><br>
                    <a href="{% url 'progress:step5' %}" class="special">Learn more</a>
                </div>
            </div>
        </section>

    </section>
</div>
{% endblock %}

progress/templates/step_1.html
{% extends 'base.html' %}
{% block content %}
{% include 'header.html' %}
{% include 'navbar.html' %}
{% load static %}
<div class="blog-wrapper section-padding-100">
<div class="row mt-5">
    <div class="col-12 text-center">
      <h1><strong>Step1. 웹 크롤링</strong></h1>
        {{ post.content }}
    </div>
  </div>
    <br>
    <br>
    <br>
<div id="wrapper">
    <div id="main">
            <article class="post">
                <header>
                    <div class="title text-center">
                        <h3><strong>네이버 관객 & 평론가</strong></h3>
                    </div>
                </header>
                <img src="{% static 'assets/img/네이버함수크롤링.jpeg' %}" alt=""><br>
                <img src="{% static 'assets/img/네이버관객크롤링.jpeg' %}" alt=""><br>
                <img src="{% static 'assets/img/네이버평론가크롤링.jpeg' %}" alt=""><br>
            </article>
        <br>
            <article class="post">
                <header>
                    <div class="title text-center">
                        <h3><strong>다음 관객</strong></h3>
                    </div>
                </header>
                <img src="{% static 'assets/img/다음관객크롤링.jpeg' %}" alt=""><br>
            </article>
        <br>
            <article class="post">
                <header>
                    <div class="title text-center">
                        <h3><strong>IMDB 관객</strong></h3>
                    </div>
                </header>
                <img src="{% static 'assets/img/imdb크롤링.jpeg' %}" alt=""><br>
                <img src="{% static 'assets/img/imdb크롤링 (2).jpeg' %}" alt="">
            </article>
        <br>
            <article class="post">
                <header>
                    <div class="title text-center">
                        <h3><strong>로튼토마토 관객 & 평론가</strong></h3>
                    </div>
                </header>
                <img src="{% static 'assets/img/로튼토마토관객크롤링.jpg' %}" alt=""><br>
                <img src="{% static 'assets/img/로튼토마토평론가크롤링.jpg' %}" alt="">
            </article>
</div>
</div>
    <a href="{% url 'progress:progress_list' %}"><button class = "btn btn-primary">목록으로</button></a>
</div>
{% endblock %}

progress/templates/step_2.html
{% extends 'base.html' %}
{% block content %}
{% include 'header.html' %}
{% include 'navbar.html' %}
{% load static %}
<div class="blog-wrapper section-padding-100">
<div class="row mt-5">
    <div class="col-12 text-center">
      <h1><strong>Step2. 워드 클라우드</strong></h1>
        {{ post.content }}
    </div>
  </div>
    <br>
    <br>
    <br>
<div id="wrapper">
    <div id="main">
            <article class="post">
                <header>
                    <div class="title text-center">
                        <h3><strong>네이버 관객</strong></h3>
                    </div>
                </header>
                <img src="{% static 'assets/img/네이버관객워드클라우드(1).jpeg' %}" alt=""><br>
              <img src="{% static 'assets/img/네이버관객워드클라우드(2).jpeg' %}" alt=""><br>
              <img src="{% static 'assets/img/네이버관객워드클라우드(3).jpeg' %}" alt=""><br>
              <img src="{% static 'assets/img/네이버관객워드클라우드(4).jpeg' %}" alt=""><br>
            </article>
        <br>
            <article class="post">
                <header>
                    <div class="title text-center">
                        <h3><strong>다음 관객</strong></h3>
                    </div>
                </header>
                <img src="{% static 'assets/img/범죄도시다음워드클라우드.jpeg' %}" alt=""><br>
            </article>
        <br>
            <article class="post">
                <header>
                    <div class="title text-center">
                        <h3><strong>IMDB 관객</strong></h3>
                    </div>
                </header>
                <img src="{% static 'assets/img/imdb기생충워드클라우드.jpeg' %}" alt=""><br>
              <img src="{% static 'assets/img/imdb기생충워드클라우드(2).jpeg' %}" alt="">
            </article>
        <br>
            <article class="post">
                <header>
                    <div class="title text-center">
                        <h3><strong>로튼토마토 관객 & 평론가</strong></h3>
                    </div>
                </header>
                <img src="{% static 'assets/img/로튼토마토관객워드클라우드.jpg' %}" alt=""><br>
              <img src="{% static 'assets/img/로튼토마토관객워드클라우드(2).jpg' %}" alt="">
            </article>
</div>
</div>
    <a href="{% url 'progress:progress_list' %}"><button class = "btn btn-primary">목록으로</button></a>
</div>

{% endblock %}

progress/templates/step_3.html
{% extends 'base.html' %}
{% block content %}
{% include 'header.html' %}
{% include 'navbar.html' %}
{% load static %}
<div class="blog-wrapper section-padding-100">
<div class="row mt-5">
    <div class="col-12 text-center">
      <h1><strong>Step3. 감성 분석</strong></h1>
        {{ post.content }}
    </div>
  </div>
    <br>
    <br>
    <br>
<div id="wrapper">
    <div id="main">
            <article class="post">
                <header>
                    <div class="title text-center">
                        <h3><strong>네이버 관객 라벨링</strong></h3>
                    </div>
                </header>
                <img src="{% static 'assets/img/네이버관객감성라벨링(1).jpeg' %}" alt=""><br>
              <img src="{% static 'assets/img/네이버관객감성라벨링(2).jpeg' %}" alt=""><br>
              <img src="{% static 'assets/img/네이버관객감성라벨링(3).jpeg' %}" alt=""><br>
              <img src="{% static 'assets/img/네이버관객감성라벨링(4).jpeg' %}" alt=""><br>
              <img src="{% static 'assets/img/네이버관객감성라벨링(5).jpeg' %}" alt=""><br>
              <img src="{% static 'assets/img/네이버관객감성라벨링(6).jpeg' %}" alt=""><br>
              <img src="{% static 'assets/img/네이버관객감성라벨링(7).jpeg' %}" alt=""><br>
              <img src="{% static 'assets/img/네이버관객감성라벨링(8).jpeg' %}" alt=""><br>
              <img src="{% static 'assets/img/네이버관객감성라벨링(9).jpeg' %}" alt=""><br>
              <img src="{% static 'assets/img/네이버관객감성라벨링(10).jpeg' %}" alt=""><br>
              <img src="{% static 'assets/img/네이버관객감성라벨링(11).jpeg' %}" alt=""><br>
            </article>
        <br>
            <article class="post">
                <header>
                    <div class="title text-center">
                        <h3><strong>다음 관객 라벨링</strong></h3>
                    </div>
                </header>
                <img src="{% static 'assets/img/다음관객감성라벨링(1).jpeg' %}" alt=""><br>
              <img src="{% static 'assets/img/다음관객감성라벨링(2).jpeg' %}" alt=""><br>
              <img src="{% static 'assets/img/다음관객감성라벨링(3).jpeg' %}" alt=""><br>
              <img src="{% static 'assets/img/다음관객감성라벨링(4).jpeg' %}" alt=""><br>
            </article>
        <br>
            <article class="post">
                <header>
                    <div class="title text-center">
                        <h3><strong>LSTM 모델</strong></h3>
                    </div>
                </header>
                <img src="{% static 'assets/img/네이버관객감성머신러닝(1).jpeg' %}" alt=""><br>
              <img src="{% static 'assets/img/네이버관객감성머신러닝(2).jpeg' %}" alt=""><br>
              <img src="{% static 'assets/img/네이버관객감성머신러닝(3).jpeg' %}" alt="">
            </article>
</div>
</div>
    <a href="{% url 'progress:progress_list' %}"><button class = "btn btn-primary">목록으로</button></a>
</div>
{% endblock %}

progress/templates/step_4.html
{% extends 'base.html' %}
{% block content %}
{% include 'header.html' %}
{% include 'navbar.html' %}
{% load static %}
<div class="blog-wrapper section-padding-100">
<div class="row mt-5">
    <div class="col-12 text-center">
      <h1><strong>Step4. 흥행요인 분석</strong></h1>
        {{ post.content }}
    </div>
  </div>
    <br>
    <br>
    <br>
<div id="wrapper">
    <div id="main">
            <article class="post">
                <header>
                    <div class="title text-center">
                        <h3><strong>흥행 요인 상세 분석</strong></h3>
                    </div>
                </header>
                <img src="{% static 'assets/img/흥행요인분석(1).jpeg' %}" alt=""><br>
              <img src="{% static 'assets/img/흥행요인분석(2).jpeg' %}" alt="">
            </article>
</div>
</div>
    <a href="{% url 'progress:progress_list' %}"><button class = "btn btn-primary">목록으로</button></a>
</div>

{% endblock %}

progress/templates/step_5.html
{% extends 'base.html' %}
{% block content %}
{% include 'header.html' %}
{% include 'navbar.html' %}
{% load static %}
<div class="blog-wrapper section-padding-100">
<div class="row mt-5">
    <div class="col-12 text-center">
      <h1><strong>Step5. 영화 추천</strong></h1>
        {{ post.content }}
    </div>
  </div>
    <br>
    <br>
    <br>
<div id="wrapper">
    <div id="main">
            <article class="post">
                <header>
                    <div class="title text-center">
                        <h3><strong>흥행 요인 상세 분석</strong></h3>
                    </div>
                </header>
                <img src="{% static 'assets/img/유사도분석추천(1).jpeg' %}" alt=""><br>
              <img src="{% static 'assets/img/유사도분석추천(2).jpeg' %}" alt=""><br>
              <img src="{% static 'assets/img/유사도분석추천(3).jpeg' %}" alt="">
            </article>
</div>
</div>
    <a href="{% url 'progress:progress_list' %}"><button class = "btn btn-primary">목록으로</button></a>
</div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">

    <title>WTD</title>
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />

    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
</head>
<body>
<body>
    <!-- 기본 템플릿 안에 삽입될 내용 Start -->
    {% block content %}
    <!--  base.html을 상속받는 템플릿에서 개별적으로 구현해야 하는 영역-->
    {% endblock %}
    <!-- 기본 템플릿 안에 삽입될 내용 End -->


    <!-- Footer-->
    <footer class="footer text-faded text-center py-5" id="footer">
        <div class="container"><p class="m-0 small"><a href="#"> Copyright &copy; WTD; We're Trend Doker </a></p></div>
        <p class="m-0 small"><a href="https://www.freepik.com/free-vector/modern-black-friday-background-with-vhs-effect-template_10308948.htm#query=movie&position=18&from_view=search&track=sph">Background image by BiZkettE1</a> on Freepik</p>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="{% static 'js/scripts.js' %}"></script>
</body>
</html>

templates/header.html
    <header>
        <h1 class="site-heading text-center text-faded d-none d-lg-block">
            <span class="site-heading-upper text-primary mb-3">WTD</span>
            2019 vs 2022년 천만 영화 흥행 요인 분석
        </h1>
    </header>

templates/navbar.html
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-dark py-lg-4" id="mainNav">
    <div class="container">
        <a class="navbar-brand text-uppercase fw-bold d-lg-none" href="{% url 'home:index' %}">WTD</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mx-auto">
                <li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="{% url 'home:index' %}">Home</a></li>
                <li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="{% url 'home:intro' %}">Intro</a></li>
                <li class="dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" aria-expanded="false" href="{% url 'progress:progress_list' %}"><span>Progress</span> <i class="bi bi-chevron-down"></i></a>
                    <ul class="dropdown-menu">
                      <li><a href="{% url 'progress:step1' %}">STEP 1. 웹 크롤링</a></li>
                      <li><a href="{% url 'progress:step2' %}">STEP 2. 워드 클라우드</a></li>
                      <li><a href="{% url 'progress:step3' %}">STEP 3. 감성분석</a></li>
                      <li><a href="{% url 'progress:step4' %}">STEP 4. 흥행요인분석</a></li>
                      <li><a href="{% url 'progress:step5' %}">STEP 5. 유사한 영화 추천</a></li>
                    </ul>
                </li>
                <li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="{% url 'result:result_list' %}">Result</a></li>
            </ul>
        </div>
    </div>
</nav>